### ISSUE TITLE
ASTPass creates UnkownNode

### ISSUE THREAD

**Issue by popthink** [plume-oss/plume#100]
trying to make fix.

**Comment by popthink** [comment]
changed return type of createNewExpr
(NewTypeRefBuilder[?? node]  => NewUnknownBuilder[Lang-specific node])

**Comment by DavidBakerEffendi** [comment]
Yeah I made that change at a point since I noticed that this was how Ocular handled new expressions. New expressions are OOP dependent. But a new expression might require a call to the constructor of the `TypeDecl`

**Comment by popthink** [comment]
Closed.
