### ISSUE TITLE
have to consider what edges are needed in the specific Pass before run the Pass.

### ISSUE THREAD

**Issue by popthink** [plume-oss/plume#102]
Method has cfgNode to retrieve cfgNodes connected with the Method through 'Contains' edge.
as following.
```
def cfgNode: Traversal[nodes.CfgNode] =
           method._containsOut.asScala.collect { case cfgNode: nodes.CfgNode => cfgNode }
```

When trying to re-use Passes of scpg, the Pass-caller should load proper edges and nodes with driver as expected by Passes of scpg.

For instance, ReachingDefPass requires methods as input which should have not only edges of Contains but also edges for Method-Stub(Method Head, Param, Return) within a temp graph.

ContainsEdgePass requires ASTNodes which connected with its AST neighbor.

**Comment by popthink** [comment]
Perhaps, we may need to create a proxy-node which provides traversal with driver.

**Comment by DavidBakerEffendi** [comment]
Currently `getMethod` does this as you will see under the tests here: https://github.com/plume-oss/plume/blob/master/plume/src/test/kotlin/io/github/plume/oss/drivers/TinkerGraphDriverIntTest.kt

Look at `testGetMethodBody`. The only issue that is linked to #93 is that the passes are receiving method bodies that it may not expect. Right now I'm trying to improve performance but after that I'll look at this.
