### ISSUE TITLE
Nested Body Blocks

### ISSUE THREAD

**Issue by DavidBakerEffendi** [plume-oss/plume#147]
So far only a method has a block, but to be correct, Plume lacks the following blocks:
- A block for an IF and ELSE body
- A block for SWITCH statement bodies

Plume cannot yet determine a while/do-while/for-loop (and using bytecode, that is challenging to do accurately) so these two are fine to cover now. This is more of an AST problem as UnitGraphs are CFGs so perhaps a different representation is required for this.

**Comment by popthink** [comment]
Does this problem make some confliction on query?

**Comment by DavidBakerEffendi** [comment]
Not that I'm aware of. CONTROL_STRUCTURE and BLOCK vertices are only really a thing on the source-code frontends anyway since it's more to do with the AST. Most of the AST info is lost in bytecode anyway so the only important stuff is that the CFG and data dependencies are correct.

That's why I've marked this as low priority.

**Comment by DavidBakerEffendi** [comment]
JVM bytecode and Jimple have flat ASTs - so no need to worry about this issue
