### ISSUE TITLE
Local publishing?

### ISSUE THREAD

**Issue by fabsx00** [plume-oss/plume#41]
I tried `gradlew publishToMavenLocal` but that crashed. Is there any other way to publish jars locally? This would allow changes in plume to be tested in depending projects before merging them.

**Comment by DavidBakerEffendi** [comment]
This seems to be a bug introduced from adding `from components.java` to publications in `build.gradle`. Will see if there is a quick fix.

**Comment by DavidBakerEffendi** [comment]
This issue is fixed in v0.0.3 and is now on develop
