### ISSUE TITLE
Missing methods

### ISSUE THREAD

**Issue by fabsx00** [plume-oss/plume#46]
I've attached a jar (rename from .zip to .jar) and the log I get when running plume via `joern-parse --language java <thejar>`. All methods in the class `Metrics` are missing for some reason. As you can see in the log, the file is still identified, however, none of the methods are projected.
[log.txt](https://github.com/plume-oss/plume/files/5748783/log.txt)

[batteries_2.13-0.0.7+3-ca0025c4.zip](https://github.com/plume-oss/plume/files/5748787/batteries_2.13-0.0.7%2B3-ca0025c4.zip)

**Comment by DavidBakerEffendi** [comment]
@fabsx00 Is this still happening in the latest version of Plume?
