### ISSUE TITLE
TYPE_DECL Potential Duplication and Erroneous Updates

### ISSUE THREAD

**Issue by popthink** [plume-oss/plume#78]
Extractor initializes 'programStructure' which is deep-copied from current graph.

After that, Extractor filters duplicated Types & Classes, etc with the 'programStructure'.

Thus while adding external type into Graph, The Extractor can't filter them then create all.

Extractor.kt
```
        createExternalTypes(
            classStream = classStream,
            typeStream = classStream.asSequence().map { it.fields }.flatten().map { it.type }
        )
        createExternalTypes(
            classStream = classStream,
            typeStream = graphs.asSequence().map { it.body.locals + it.body.parameterLocals }.flatten().map { it.type }
        ) 
```

```
    private fun createExternalTypes(classStream: List<SootClass>, typeStream: Sequence<soot.Type>) {

        typeStream.distinct()
            .filter { t -> !classStream.any { it.name == t.toString() } }
            .filter {
                !programStructure.nodes(TYPE_DECL).asSequence().any { n -> n.property(FULL_NAME) == it.toString() }
            }
```

programStructure  => driver.getWholeGraph() ?

Thank you

**Comment by popthink** [comment]
and.. While Constructing the CPGs for methods.

following code produces Structure of every class used in method, even if the classes are created in 'createExternalTypes'.

So filter may need to remove duplicate "TYPEDECL" ( one related with "unknown" file, the another related with "??.class" file.)

or we may update properties of "TYPEDECL" vertex to point proper "FILE" vertex, not "unknown".

```
        graphs.map(this::constructCPG)
            .toList().asSequence()
            .map(this::constructCallGraphEdges)
            .map { it.declaringClass }.distinct().toList()
            .filterNot { classStream.contains(it) }  /* Filter */
            .forEach(this::constructStructure)
```

**Comment by DavidBakerEffendi** [comment]
Thanks for the find, okay so v0.2.7 is going to add a method to the driver called `getProgramTypeData` which gets a sub-graph of all vertices and edges with the labels found in SCPG's `io.shiftleft.semanticcpg.passes.linking.linker.Linker` pass. 

I think that this `getProgramTypeData` will be well suited for dealing with this issue and I will most likely get to it tomorrow. Here is the PR that adds the new method [PR #79](https://github.com/plume-oss/plume/pull/79).

It definitely won't hurt to add the change as listed in the second comment, as I know `constructStructure` tries to filter duplicates by looking at if the `FILE` exists with:
```kotlin
 private fun constructStructure(cls: SootClass) {
        if (programStructure.nodes(FILE).asSequence()
                .none { it.property(NAME) == SootToPlumeUtil.sootClassToFileName(cls) }
        ) {
        ...
}
```
But you've made me realize that if I say compile 2 classes where `ClassA` calls a method from `ClassB` but I first project `ClassA` and only later project `ClassB` then `ClassB` will point to the unknown `FILE` and either duplicated or not updated as an internal class.
