### ISSUE TITLE
 ContainsEdgePass in postProject method missed some node should be generated.

### ISSUE THREAD

**Issue by popthink** [plume-oss/plume#97]
ContainsEdgePass doesn't handle astNodes as expected.
In postProject, the pass only processes AstNode of methods.
```
driver.getPropertyFromVertices<String>(FULL_NAME, METHOD).forEach { mName ->
            driver.getMethod(mName).use { g ->
                PlumeTimer.measure(ExtractorTimeKey.SCPG_PASSES) {
                    // Avoid duplication
                    if (!g.edges(REACHING_DEF).hasNext()) {
                        val cpg = Cpg.apply(g)
                        val methods = g.nodes().asSequence().toList()
                        runParallelPass(methods.filterIsInstance<AstNode>(), ContainsEdgePass(cpg))
```

on the other hands, ContainsEdgepass is supposed to handle AstNodes of Method, TYPE_DECL, FILE as Input of runOnPart

```
  private val sourceTypes = List(
    NodeTypes.METHOD,
    NodeTypes.TYPE_DECL,
    NodeTypes.FILE
  )
```

**Comment by popthink** [comment]
To handle this issue, I just wrote homebrew fix-code.
```
    fun postProject(): Extractor {
        PlumeTimer.measure(ExtractorTimeKey.SCPG_PASSES){
            val cpg = Cpg.apply(driver.getWholeGraph())
            val astNodesOrigin = ContainsEdgePass(cpg).partIterator()
            val astNodes = CollectionConverters.IteratorHasAsJava(astNodesOrigin).asJava().asSequence().toList()
            runParallelPass(astNodes , ContainsEdgePass(cpg))
```

**Comment by popthink** [comment]
After we fix it, we can reproduce REACH DEF issue #59 with plume

**Comment by DavidBakerEffendi** [comment]
Ah yes my first mistake was that in `getMethod` there is an optional boolean parameter that adds the method body - default it doesn't :sweat_smile:. I used to use `getWholeGraph` but this will crash remote databases since the transactions take up too much memory etc. But there are better ways to return graphs in parts.

**Comment by DavidBakerEffendi** [comment]
Perhaps the ideal strategy would be to get all the methods one-by-one and then obtain all the file and type decls then connect them in an OverflowDb instance to feed

**Comment by DavidBakerEffendi** [comment]
I'm working on a multi-threaded pass that will converge all METHOD vertices. There are already contains edges created for types and files in Plume passes and I will eventually do the same for methods. The big one are the method bodies.
